import { ref, set, get } from 'firebase/database';
import { rtdb } from '../config/firebase';
import { Event } from '../types';

export const INITIAL_EVENTS: Event[] = [];

export class EventDatabaseService {
  /**
   * Save or Update an event in Firebase Realtime Database under events/{eventId}
   */
  public static async saveEventToRealtimeDB(event: Event): Promise<void> {
    try {
      const eventRef = ref(rtdb, `events/${event.id}`);
      await set(eventRef, {
        ...event,
        updatedAt: new Date().toISOString(),
      });
    } catch (err) {
      console.warn('Firebase RTDB Event Save Notice:', err);
    }
  }

  /**
   * Fetch all events directly from Firebase Realtime Database
   */
  public static async getEventsFromRealtimeDB(): Promise<Event[]> {
    try {
      const eventsRef = ref(rtdb, 'events');
      const snapshot = await get(eventsRef);

      if (snapshot.exists()) {
        const data = snapshot.val() as Record<string, Event>;
        return Object.values(data);
      }
    } catch (err) {
      console.warn('Firebase RTDB Fetch Events Notice:', err);
    }

    return [];
  }

  /**
   * Seed method disabled - events are 100% user-generated by Organizers
   */
  public static async seedEventsIfEmpty(): Promise<void> {
    // Zero auto-seeding
  }
}
